name: 'add event to my blog'
description: 'add event to my blog'
author: 'fzdwx'
branding:
  icon: 'archive'
  color: 'white'
inputs:
  token:
    required: true
    description: 'the repo PAT or GITHUB_TOKEN'
    default: ${{ github.token }}
  public:
    default: false
    description: 'allow other peoples issues to be submitted as notes,default deny'
  issueNumber:
    required: true
    description: 'current issue number.'
  username:
    description: 'your git name'
    default: 'fzdwx'
  email:
    description: 'your git email'
    default: 'likelovec@gmail.com'
runs:
  using: 'node16'
  main: 'dist/index.js'